
/**
 * Created by 向光性 on 2017/7/14.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logisticsui;
import java.awt.Color;

/**
 *
 * @author 向光性
 */
public class SignCopy extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignCopy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        tipDialog = new javax.swing.JDialog();
        tip = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        option = new javax.swing.JComboBox<>();
        passwordAgain = new javax.swing.JTextField();

        tipDialog.setTitle("警告");
        tipDialog.setAlwaysOnTop(true);
        tipDialog.setIconImage(null);
        tipDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        tipDialog.setResizable(false);

        tip.setText("账号或密码填写错误");

        confirm.setText("确定");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tipDialogLayout = new javax.swing.GroupLayout(tipDialog.getContentPane());
        tipDialog.getContentPane().setLayout(tipDialogLayout);
        tipDialogLayout.setHorizontalGroup(
                tipDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipDialogLayout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addComponent(tip)
                                .addGap(40, 40, 40))
                        .addGroup(tipDialogLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(confirm)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tipDialogLayout.setVerticalGroup(
                tipDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tipDialogLayout.createSequentialGroup()
                                .addContainerGap(45, Short.MAX_VALUE)
                                .addComponent(tip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirm)
                                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("登陆");
        setAlwaysOnTop(true);
        setResizable(false);

        signin.setText("登陆");
        signin.setToolTipText("");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        username.setForeground(java.awt.Color.lightGray);
        username.setText("用户名");
        username.setToolTipText("");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });

        password.setForeground(java.awt.Color.lightGray);
        password.setText("密码");
        password.setToolTipText("");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });

        option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "管理员", "采购员", "提货员" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(password)
                                                        .addComponent(username)
                                                        .addComponent(option, 0, 120, Short.MAX_VALUE)
                                                        .addComponent(passwordAgain))))
                                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(62, Short.MAX_VALUE)
                                .addComponent(option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passwordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(signin)
                                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if(username.getText().equals("用户名")){
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(username.getText().equals("用户名")){
            username.setForeground(Color.LIGHT_GRAY);
        }
    }

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if(password.getText().equals("密码")){
            password.setText("");
            password.setForeground(Color.BLACK);
        }
    }

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(password.getText().equals("密码")){
            password.setForeground(Color.LIGHT_GRAY);
        }
    }

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String[] info = new String[4];
        info[0] = String.valueOf(option.getSelectedItem());
        info[1] = username.getText();
        info[2] = password.getText();
        info[3] = passwordAgain.getText();

        // 判断用户类型
        String userType = info[0] = String.valueOf(option.getSelectedItem());

        // 根据登录用户类型验证用户名以及密码进行登陆
        // 登陆后关闭打开新界面
        if(userType.equals("管理员")){
            ManagerHomePage managerHomePage = new ManagerHomePage();
            managerHomePage.setVisible(true);
        } else if(userType.equals("采购员")){
            PurchaserHomePage purchaserHomePage = new PurchaserHomePage();
            purchaserHomePage.setVisible(true);
        } else if(userType.equals("提货员")){
            PickerHomePage pickerHomePage = new PickerHomePage();
            pickerHomePage.setVisible(true);
        } else {
            tipDialog.pack();
            tipDialog.setLocationRelativeTo(null);
            tipDialog.setVisible(true);
        }

//        // 关闭当前窗口
//        this.dispose();
    }

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        tipDialog.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignCopy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> option;
    private javax.swing.JTextField password;
    private javax.swing.JTextField passwordAgain;
    private javax.swing.JButton signin;
    private javax.swing.JLabel tip;
    private javax.swing.JDialog tipDialog;
    private javax.swing.JTextField username;
    // End of variables declaration
}
